In [ ]:
import tensorflow as tf
import numpy as np
# tf.InteractiveSession()
a=tf.ones((2,2),dtype=tf.float32,name='zeros')
b=tf.ones((2,2))
tf.reduce_sum(a,reduction_indices=1).eval()
tf.reduce_sum(b,reduction_indices=1).eval()

In [16]:
tf.reduce_sum(b,reduction_indices=1).eval()

array([ 2.,  2.], dtype=float32)

In [18]:
# dir(a)
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [21]:
tf.reshape(a,(1,4)).eval()

array([[ 0.,  0.,  0.,  0.]], dtype=float32)

In [23]:
a=tf.zeros((2,2))
print(a)

Tensor("zeros_12:0", shape=(2, 2), dtype=float32)


In [24]:
print(a.eval())

[[ 0.  0.]
 [ 0.  0.]]


In [27]:
a=tf.constant(1)
b=tf.constant(2)
c=a*b
with tf.Session() as sess:
    print(c.eval())
    print(sess.run(c))

2
2


In [44]:
rv=tf.Variable(tf.random_normal((2,2)),name='rand_var')#name no space
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())# var must initializer 
    print(sess.run(rv))

        # 

    
    # sess.run(tf.global_variables_initializer())

[[-1.69036782 -0.41778001]
 [ 0.74713677 -0.42180467]]


In [47]:
var_1=tf.Variable(0,name='var_1')
add_op=tf.add(var_1,tf.constant(1))
upd_op=tf.assign(var_1,add_op)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())# var must initializer 
    for i in range(5):
        print(sess.run(upd_op))
        # print(sess.run([mul_x_y,final_op]))

1
2
3
4
5


In [53]:
x_=tf.placeholder(tf.float32,shape=[4,2],name='x-input')
y_=tf.placeholder(tf.float32,shape=[4,1],name='y-input')
w1=tf.Variable(tf.random_uniform([2,2],-1,1),name='w1')
w2=tf.Variable(tf.random_uniform([2,1],-1,1),name='w2')
b1=tf.Variable(tf.random_uniform([2]),name='b1')
b2=tf.Variable(tf.random_uniform([1]),name='b2')
z2=tf.sigmoid(tf.matmul(x_,w1)+b1)
pred=tf.sigmoid(tf.matmul(z2,w2)+b2)
cost=tf.reduce_mean(((y_*tf.log(pred))+((1-y_)*tf.log(1-pred)))*-1)
learning_rate=0.001;
train_step=tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)
XOR_X=[[0,0],[0,1],[1,0],[1,1]]
YOR_Y=[[0],[1],[1],[0]]
init=tf.global_variables_initializer()
sess=tf.Session()
writer=tf.summary.FileWriter("./Downloads/XOR1_ligs",sess.graph)
sess.run(init)
for i in range(100000):
    sess.run(train_step,feed_dict={x_:XOR_X,y_:YOR_Y})
    if i %10000==0:
        print('prediction:',sess.run(pred,feed_dict={x_:XOR_X,y_:YOR_Y}))
        print('Weights from input to hidden layer:', sess.run(w1))
        print('Bias in the hidden layer:', sess.run(b1))
        print('Weights from hidden layer to output layer:', sess.run(w2))
        print('Bias in the output layer:', sess.run(b2))
        print('Cost:', sess.run(cost, feed_dict={x_: XOR_X, y_: YOR_Y}))
print('Final Prediction', sess.run(pred, feed_dict={x_: XOR_X, y_: YOR_Y}))

Instructions for updating:
Use `tf.global_variables_initializer` instead.


('prediction:', array([[ 0.45226488],
       [ 0.45106032],
       [ 0.4413617 ],
       [ 0.43973646]], dtype=float32))
('Weights from input to hidden layer:', array([[ 0.02618782,  0.33743128],
       [ 0.13070035, -0.12774344]], dtype=float32))
('Bias in the hidden layer:', array([ 0.96141601,  0.70862335], dtype=float32))
('Weights from hidden layer to output layer:', array([[-0.83753651],
       [-0.56852025]], dtype=float32))
('Bias in the output layer:', array([ 0.79531807], dtype=float32))
('Cost:', 0.69883907)


('prediction:', array([[ 0.50436771],
       [ 0.50410062],
       [ 0.49545571],
       [ 0.49468878]], dtype=float32))
('Weights from input to hidden layer:', array([[ 0.00358304,  0.33750454],
       [ 0.12147013, -0.15015963]], dtype=float32))
('Bias in the hidden layer:', array([ 0.94528109,  0.69900477], dtype=float32))
('Weights from hidden layer to output layer:', array([[-0.76074642],
       [-0.49993724]], dtype=float32))
('Bias in the output layer:', array([ 0.8992759], dtype=float32))
('Cost:', 0.69293964)


('prediction:', array([[ 0.50423801],
       [ 0.50446135],
       [ 0.4956578 ],
       [ 0.49528527]], dtype=float32))
('Weights from input to hidden layer:', array([[-0.01034695,  0.34402433],
       [ 0.12157366, -0.16612476]], dtype=float32))
('Bias in the hidden layer:', array([ 0.94520718,  0.70130038], dtype=float32))
('Weights from hidden layer to output layer:', array([[-0.75986761],
       [-0.50293732]], dtype=float32))
('Bias in the output layer:', array([ 0.90037268], dtype=float32))
('Cost:', 0.69288874)


('prediction:', array([[ 0.50387412],
       [ 0.50455606],
       [ 0.49558467],
       [ 0.49556822]], dtype=float32))
('Weights from input to hidden layer:', array([[-0.02418809,  0.35158977],
       [ 0.12306068, -0.18226102]], dtype=float32))
('Bias in the hidden layer:', array([ 0.94520718,  0.70375305], dtype=float32))
('Weights from hidden layer to output layer:', array([[-0.75931305],
       [-0.50672418]], dtype=float32))
('Bias in the output layer:', array([ 0.90132439], dtype=float32))
('Cost:', 0.69283539)


('prediction:', array([[ 0.50350934],
       [ 0.50462216],
       [ 0.49548468],
       [ 0.49578771]], dtype=float32))
('Weights from input to hidden layer:', array([[-0.03811112,  0.36018211],
       [ 0.12586668, -0.19864723]], dtype=float32))
('Bias in the hidden layer:', array([ 0.94520718,  0.70673329], dtype=float32))
('Weights from hidden layer to output layer:', array([[-0.758717 ],
       [-0.5108965]], dtype=float32))
('Bias in the output layer:', array([ 0.90256453], dtype=float32))
('Cost:', 0.69277817)


('prediction:', array([[ 0.50317848],
       [ 0.50470006],
       [ 0.49539074],
       [ 0.49597993]], dtype=float32))
('Weights from input to hidden layer:', array([[-0.05223458,  0.36985937],
       [ 0.12999259, -0.21535259]], dtype=float32))
('Bias in the hidden layer:', array([ 0.94520718,  0.70978492], dtype=float32))
('Weights from hidden layer to output layer:', array([[-0.75813472],
       [-0.51560199]], dtype=float32))
('Bias in the output layer:', array([ 0.9043206], dtype=float32))
('Cost:', 0.69271576)


('prediction:', array([[ 0.5028668 ],
       [ 0.50477791],
       [ 0.49529597],
       [ 0.49613789]], dtype=float32))
('Weights from input to hidden layer:', array([[-0.06668385,  0.38066012],
       [ 0.13543867, -0.23246948]], dtype=float32))
('Bias in the hidden layer:', array([ 0.94520718,  0.7133612 ], dtype=float32))
('Weights from hidden layer to output layer:', array([[-0.75754702],
       [-0.52070963]], dtype=float32))
('Bias in the output layer:', array([ 0.90648603], dtype=float32))
('Cost:', 0.69264662)


('prediction:', array([[ 0.50256854],
       [ 0.50485504],
       [ 0.49519411],
       [ 0.49625728]], dtype=float32))
('Weights from input to hidden layer:', array([[-0.08157626,  0.39264044],
       [ 0.14222829, -0.25007036]], dtype=float32))
('Bias in the hidden layer:', array([ 0.94520718,  0.71719891], dtype=float32))
('Weights from hidden layer to output layer:', array([[-0.75697035],
       [-0.52632946]], dtype=float32))
('Bias in the output layer:', array([ 0.90909469], dtype=float32))
('Cost:', 0.69256914)


('prediction:', array([[ 0.50228244],
       [ 0.50493485],
       [ 0.4950861 ],
       [ 0.49633986]], dtype=float32))
('Weights from input to hidden layer:', array([[-0.09703336,  0.40587032],
       [ 0.15038928, -0.26823857]], dtype=float32))
('Bias in the hidden layer:', array([ 0.94520718,  0.72137368], dtype=float32))
('Weights from hidden layer to output layer:', array([[-0.75649351],
       [-0.53251982]], dtype=float32))
('Bias in the output layer:', array([ 0.91225642], dtype=float32))
('Cost:', 0.6924814)


('prediction:', array([[ 0.50200456],
       [ 0.50501704],
       [ 0.49497116],
       [ 0.49638408]], dtype=float32))
('Weights from input to hidden layer:', array([[-0.11317848,  0.42043981],
       [ 0.15996957, -0.28706014]], dtype=float32))
('Bias in the hidden layer:', array([ 0.94520718,  0.72614205], dtype=float32))
('Weights from hidden layer to output layer:', array([[-0.75613707],
       [-0.53931141]], dtype=float32))
('Bias in the output layer:', array([ 0.91602385], dtype=float32))
('Cost:', 0.69238114)


('Final Prediction', array([[ 0.50172997],
       [ 0.50510269],
       [ 0.49484649],
       [ 0.49638826]], dtype=float32))
